### ISSUE TITLE
Add optimization when user upload images

### ISSUE THREAD

**Issue by Im-Boss-13** [DawnBee/college-medicine-app#23]
In the backend add custom function that resizes certain images when uploaded.

**Comment by DawnBee** [comment]
> In the backend add custom function that resizes certain images when uploaded.

These are the models/components I think these could work:

- Events (800px-850px)
- Testimonials (300px-350px)
- Sim Trainings (500px)
- Faculties (600px)
- Benefactors (400px)

Other components like the 'Announcements' require to be as big as possible since it expands as wide as the viewport.

**Comment by Im-Boss-13** [comment]
> > In the backend add custom function that resizes certain images when uploaded.
> 
> These are the models/components I think these could work:
> 
> * Events (800px-850px)
> * Testimonials (300px-350px)
> * Sim Trainings (500px)
> * Faculties (600px)
> * Benefactors (400px)
> 
> Other components like the 'Announcements' require to be as big as possible since it expands as wide as the viewport.

Agreed!
