### ISSUE TITLE
Add 'Outcome Based Education' section in 'About' page

### ISSUE THREAD

**Issue by Im-Boss-13** [DawnBee/college-medicine-app#89]
Labeling this as "wontfix" since we don't have content and idea to structure this in the app yet. Plus there are a lot of stuff that we have to focus first, especially that we're on the deployment phase.

**Comment by DawnBee** [comment]
> Labeling this as "wontfix" since we don't have content and idea to structure this in the app.

Agreed!

**Comment by Im-Boss-13** [comment]
> Needs further clarification
